apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-app.fullname" . }}-config
data:
  nginx.conf: |
    server {
        listen 80;
        server_name {{ .Values.config.server_name }};
        location / {
            root {{ .Values.config.root }};
            index index.html;
        }
    }
